all: schedule.out schedule_1.out schedule_2.out

schedule.out: schedule.cpp
	g++ -o schedule.out schedule.cpp

schedule_1.out: schedule_1.cpp
	g++ -o schedule_1.out schedule_1.cpp

schedule_2.out: schedule_2.cpp
	g++ -o schedule_2.out schedule_2.cpp

clean:
	rm -f *.out 
